// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAknX261O_28-vGCkUOxqwRHVdYCDwMK4',
    appId: '1:114705556766:web:a13c266507f1c0c1f3150f',
    messagingSenderId: '114705556766',
    projectId: 'scrumboard-f0a9d',
    authDomain: 'scrumboard-f0a9d.firebaseapp.com',
    storageBucket: 'scrumboard-f0a9d.appspot.com',
    measurementId: 'G-WWJNZW0WGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_fZGLw17tFSKW8G9CqFMEdFmQ0u9t_o',
    appId: '1:114705556766:android:e6f40aa471608969f3150f',
    messagingSenderId: '114705556766',
    projectId: 'scrumboard-f0a9d',
    storageBucket: 'scrumboard-f0a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5c_2TGpSklDngQVWxre-yqVP2fUghy0',
    appId: '1:114705556766:ios:dbb73bc9e38dd4d9f3150f',
    messagingSenderId: '114705556766',
    projectId: 'scrumboard-f0a9d',
    storageBucket: 'scrumboard-f0a9d.appspot.com',
    iosClientId:
        '114705556766-p97sk6urqnsqvvgf6h0kfrdmvdvt56dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW5c_2TGpSklDngQVWxre-yqVP2fUghy0',
    appId: '1:114705556766:ios:dbb73bc9e38dd4d9f3150f',
    messagingSenderId: '114705556766',
    projectId: 'scrumboard-f0a9d',
    storageBucket: 'scrumboard-f0a9d.appspot.com',
    iosClientId:
        '114705556766-p97sk6urqnsqvvgf6h0kfrdmvdvt56dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumboard',
  );
}
